version: '3.3'

volumes:
  postgres_data: 
  static_value:
  media_value:

services:
  db:
    image: postgres:12.4
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - /uxubisg/.env
  web:
    image: uxubisg/foodgram:latest
    restart: always
    depends_on:
      - db
    env_file:
      - /uxubisg/.env
    volumes: 
      - static_value:/code/static
      - media_value:/code/media/
  nginx:
    image: nginx:1.19.9-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static:ro
      - media_value:/var/html/media:ro
    ports:
      - '80:80'
    depends_on:
      - web
