# Generated by Django 2.2.19 on 2021-06-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210613_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='style',
        ),
    ]
