# Generated by Django 2.2.19 on 2021-06-29 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210624_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Количество'),
        ),
    ]
